# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Soulless Studio
# Description of the Site
description: An ambitious indie game studio crafting our debut title with passion and precision. We're a small team with big dreams, focusing on creating unique gaming experiences that challenge conventions and captivate players.
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Indie Game Studio, Game Development, Indie Games, Gaming
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: say-hi@soulless.studio
facebook_username: 
twitter_username: 
instagram_username: soulless.studio
linkedin_username: 
github_username: soulless-studio
youtube_channel_id: 
reddit_username: soulless_studio
behance_username: 
dribbble_username: 
spotify_username: 
tiktok_username: soulless.studio

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Soulless Studio
# URL for the Image of the Author
author-image: /assets/images/logo.png
# 60 Words About the Author
author-about: We are an independent game development studio dedicated to creating immersive and thought-provoking gaming experiences. Our first title is currently in development, combining innovative gameplay mechanics with atmospheric storytelling. Follow our journey as we craft our debut game with meticulous attention to detail and a passion for pushing creative boundaries.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://soulless.studio

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "news/:categories/:year/:month/:day/:title/"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
