title: Soulless Studio
email: say-hi@soulless.studio
description: >-
  Game development studio creating amazing experiences
baseurl: ""
url: 'https://soulless-studio.github.io'
theme: minima

header_pages:
  - index.md
  - games.md
  - about.md
  - contact.md