name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - production
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set CNAME
        run: |
          if [ "${{ github.ref }}" = "refs/heads/production" ]; then
            echo "${{ secrets.PRODUCTION_DOMAIN }}" > CNAME
          else
            echo "${{ secrets.DEVELOPMENT_DOMAIN }}" > CNAME
          fi
      - name: Set URL in config
        run: |
          if [ "${{ github.ref }}" = "refs/heads/production" ]; then
            sed -i "s|baseurl:.*|baseurl: https://${{ secrets.PRODUCTION_DOMAIN }}|g" _config.yml
          else
            sed -i "s|baseurl:.*|baseurl: https://${{ secrets.DEVELOPMENT_DOMAIN }}|g" _config.yml
          fi
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        env:
          JEKYLL_ENV: ${{ github.ref == 'refs/heads/production' && 'production' || 'development' }}
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: ${{ github.ref == 'refs/heads/production' && 'production' || 'development' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4